### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by eangulus** [karthikax/woopush-notifications#1]
Was wanting to use this plugin as there is nothing else out there intergrating PushBullet and WooCommerce.

My concern is if this is still active or not. Its not under the WordPress Plugin site, and not available to download from the official donate page, and it hasn't been touch in a year.

I do understand that simple plugins like this one do not need frequent updates, but not know if you are not needing to make changes or it has been abandond is my main concern. PS: Seems to still work in 4.3

**Comment by karthikax** [comment]
Hi.. I have developed this plugin for my personal use. I am actively using it. I am not facing any problems or issues. So there were no necessity to make changes. I dint like Wordpress rating system for opensource plugins. So did not keep it in WordPress Plugin site. Now you can download this only from github. If you face any issues i will be happy to solve.
